[package]
name = "inv-call-extract"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
log = "0.4.22"
graphviz-rust = "0.9.3"
colog = "1.3.0"
petgraph = "0.7.0"
